### PR TITLE
Better integration with Metamask

### LINKED ISSUE #17: Correctly configure MetaMask network
In my tests, it seems that the frontend does not configure the right network when connecting with MetaMask. We have to ask the user to switch to the right network if he does not have Viviani in their network list.

Please refer to https://medium.com/quick-programming/how-to-programmatically-switch-the-users-network-when-they-connect-with-metamask-6b9c761fe73b (see adding a network)

### PR DESCRIPTION
**Pull request by iosonopersia**
Closes #17.

The DesmoldSDK service gets almost completely rewritten.

A new page is shown when either Metamask isn't installed, the selected chain isn't Viviani or the user isn't logged in.
In each situation, a proper message is shown at the center of the page with an action button that allows the user to solve the problem in just a bit more than a click.

If the user didn't add the Viviani chain to its Metamask configuration, the button for switching to Viviani chain will also properly configure such chain.

Better error handling overall, with snackbar popups shown instead of using console.error (some errors can still appear in the console: they're thrown by Metamask itself).

Fixed the appearance of the two components in the TddManager page.

If the user changes chain or disconnects in the Metamask plugin, the page gets reloaded.
If the user changes account (wallet) in the Metamask plugin, the application handles this situation by updating dynamically its interfaces with the contracts.

### CODE REVIEW

**Comment by iosonopersia** [comment]
It's still a draft because I would like #20 to be merged before this one.

**Comment by relu91** [comment]
#20 merged, changing to ready for review

**Review by relu91 — CHANGES_REQUESTED** [review]
Ok, the application now is more robust, well done. Still, I found an issue. How to reproduce:
- Create a viviani network manually on your metamask wallet with (https://viviani.iex.ec/) as the RPC endpoint. 
- Switch to another network
- open the front end
- the application ask to **add** another viviani network 
- the application then switches to the newly created viviani network

The result is that now I have two viviani networks defined in my wallet. I want that the application is smart enough to figure out that I already have the correct network configured.

**Comment by relu91** [comment]
Probably the application does not know that `https://viviani.iex.ec/` is equal to `https://viviani.iex.ec`

**Comment by relu91** [comment]
Another bug:
- go to the TDD manager page
- you see your registered TDD 
- switch to an account that does not have a TDD registred
- pop up says no TDD found (which is right)
- the table still shows the old TDD registred

**Comment by iosonopersia** [comment]
**DON'T MERGE! I MADE A MESS!**

**Comment by iosonopersia** [comment]
Closing because I messed up something with the commits from this PR. I applied the requested changes and opened a new PR as a replacement for this one. Please head over to #22.

**Pull request closed without merging**
