### PR TITLE
Remove DesmoldSDK service

### PR DESCRIPTION
**Pull request by iosonopersia**
It looks like the DesmoldSDK singleton service, apart from being just a useless wrapper over the SDK library, causes some circular dependency errors (only within Firefox!).

I wasn't able to understand why such errors appear when using Firefox but, since that service isn't really needed, I decided to solve the problem by removing it and replacing it with direct calls to the SDK library.

### CODE REVIEW

**Review by relu91 — APPROVED** [review]
I'm approving the PR but I would wait for input also from @hyperloris. Services are a nice abstraction layer to avoid that SDK updates will impact a lot of other places (as you can see in this PR the service is imported in different other scripts). I see your rationale but let me think more about it.

**Comment by hyperloris** [comment]
I agree with @relu91. I usually prefer to wrap the SDK inside a service exposing only what I need. That way, it becomes easier to handle any "breaking changes" or some extra logic you may need. Let's say that, in this specific case, we can make an exception and use our SDK directly.

**Comment by iosonopersia** [comment]
Please, don't merge, I'm working on this

**Comment by iosonopersia** [comment]
Closing. The Firefox bug stopped appearing and the DesmoldSDK service will be needed for a future PR related to a better integration with the Metamask browser extension.

**Pull request closed without merging**
